### ISSUE TITLE
Allow ability to set custom hashes for filenames in malware YAML file

### ISSUE THREAD

**Issue by waymon-ho** [KC7-Foundation/kc7#108]
Allow designated filenames in "malware" yaml files to have custom preset hashes to make believable malware files, etc. for game questions & investigations. 

For example: 

Given a filename in "malware.yaml" where there's: 

filenames:
  - a.exe
  - svchost.exe
  - msdtc.exe`

Allow additional yaml setting to set hashes for each filename. If there's more than one hash, choose a random one to use. If no hashes are set, choose a randomized hash from pre-existing hashes we already assign to malware.

For example: 

hashes:
  - filename: a.exe
    hash: 42530f9f92f2440d66b96e610d07b5256566fe47af2fd6e01cd9e1cd9b85c01e
  - filename: svchost.exe
    hash: 9bd6a46182f145240e766380d2df56f299ef36dc05ed1f4637b75514c4fd051e
  - filename: svchost.exe
    hash: 0c3eff5d888cfd0c4c7f1cbc43fad5ca529e70c1a7edc6fcafadca9ebf1e3f88
  - filename: svchost.exe
    hash: b54a65ca16116b92c6fe5eb6c046b5e7e91aab377703ad51c7def93f725a8c42
  - filename: msdtc.exe
    hash: 3bd4e1f0d1d67a25c2df2c2495005089ac2b076e8a447279c505a931cef45b17

Not sure if there's a better way to just have one filename + a list of hashes on YAML.

**Comment by kkneomis** [comment]
Resolved in https://github.com/KC7-Foundation/kc7/pull/111
