### ISSUE TITLE
Implement YAML config validator for all config types

### ISSUE THREAD

**Issue by gregs1998** [KC7-Foundation/kc7#110]
Current expectations for YAML configuration layouts are ambiguous. We should add a YAML config validator (that runs either inline in the application or as a standalone app) to parse a config and identify any issues that will result in a game run error.

An existing config helper exists for Actor configs, but we need to implement validators for other config types.

**Comment by kkneomis** [comment]
Addressed in https://github.com/KC7-Foundation/kc7/pull/116
